#if defined _menu_included
 #endinput
#endif
#define _menu_included

#define TEXT_BUFFER_MAX_SIZE 1024

#define CLASS_MANAGER "Class manager"
#define RIFLEMAN "Rifleman"
#define ASSAULT "Assault"
#define SUPPORT "Support"
#define SNIPER "Sniper"
#define MG "Mg"
#define ROCKET "Rocket"
#define SELECT_ACTION "Select action"
#define ENABLE_CLASS "Enable class"
#define DISABLE_CLASS "Disable class"
#define SET_CLASS_LIMIT "Set class limit"
#define SELECT_TEAM "Select team"
#define ALLIES "Allies"
#define AXIS "Axis"
#define BOTH_TEAMS "Both teams"

#define ADMIN_MENU "adminmenu"
